---
# soe_base
soe_base_domain: ekko.com
soe_base_environment: staging
soe_base_organization: "Ekko Lab"

soe_base_timezone: Asia/Taipei
soe_base_locale: C.UTF-8

soe_base_ntp_servers:
  - time1.google.com
  - time2.google.com

soe_base_selinux_state: permissive
soe_base_selinux_policy: targeted

soe_base_crypto_policy: DEFAULT

# soe_network
soe_network_disable_ipv6: true
soe_network_dns_servers:
  - 192.168.13.216
  - 8.8.8.8
  - 8.8.4.4
soe_network_dns_search:
  - "{{ soe_base_domain }}"
