---
# soe_base
soe_base_environment: staging
soe_base_organization: "Ekko Lab"
soe_base_domain: idm.ekko.com

soe_base_timezone: Asia/Taipei
soe_base_locale: C.UTF-8

soe_base_ntp_servers:
  - time1.google.com
  - time2.google.com

soe_base_selinux_state: permissive
soe_base_selinux_policy: targeted

soe_base_crypto_policy: DEFAULT

#
soe_dns_servers:
  - 192.168.13.216
  - 8.8.8.8
  - 8.8.4.4
soe_dns_search_domains:
  - "{{ soe_base_domain }}"
